### ISSUE TITLE
Describing a tiny bit what "AWDL" means (Apple Wireless Direct Link) might help remove initial barriers to community understanding, maybe?

### ISSUE THREAD

**Issue by johnnyutahh** [Frostie314159/awdl-frame-parser#2]
Subjective comment/request...

Describing a tiny bit what "AWDL" means (Apple Wireless Direct Link...assuming this is correct?) might help remove initial barriers to community understanding, maybe?

Even a simple spell-out of the acronym in the About/Description on the github.com front page and a reference to ["stackoverflow.com answer to: What is AWDL (Apple Wireless Direct Link) and how does it work?"](https://stackoverflow.com/a/28196009/605356) might go a long ways to un-confusing people... at least it would help me.

eg: I was about to disregard [this reddit thread](https://www.reddit.com/r/rust/comments/14my1rt/a_frame_parser_for_a_proprietary_apple_protocol/) (I originally presumed it was a video-ish thing, ie, "frame" meant "video frame") until I took the time to dig deeper. (Yes, "apple wireless direct link protocol" is in the reddit post, but it's in the text below the weblink to this github page _and_ it's not capilatized... both making it easy to overlook. The point: blast it in "not easy to miss" places like the About section of the github front page.) Other people who might otherwise be interested may not take the time to dig deeper without a minor bit of explanation.

Again, subjective point, pls take it as such. 🤓

**Comment by Frostie314159** [comment]
Thanks for the feedback, I will edit the readme accordingly.

**Comment by Frostie314159** [comment]
Fixed with last [commit](https://github.com/Frostie314159/awdl-frame-parser/commit/20b86fb147408a0eed25d5dc65e12fea355e2537).
